#!/bin/bash
#
# Update script for ESVA 2.0.6.1
# This script will update your esva 2.x to the latest 2.0.x version
# This script is downloaded and executed by /usr/local/sbin/esva-update
# 
# Original author Andrew MacLachlan
# Original (c) Andrew MacLachlan
#
# For ESVA help see: http://www.esvacommunity.com/
# For changes see the 'CHANGES' File 

#############################################
# Some Settings				    #
#############################################

VERSION=2.0.6.1
sVERSION=2061
filelist=filelist.txt
wwwpath=/var/www/html

PM1="http://www.esvacommunity.com"
PM2="http://www.global-domination.org"
PM3="http://www.troublenow.org/esva"
#############################################

#############################################
# Check the Version                         #
#############################################
function VersionCheck()
{
if [ "`cat /var/esva/currentversion`" == $VERSION ]; then
   echo "[ESVA] You are already running version $VERSION, no update needed"
   exit 0
else
   echo "[ESVA] You are running esva version `cat /var/esva/currentversion`"
   echo "[ESVA] Starting upgrade to $VERSION"
   echo "[ESVA] You may see some error's during the system upgrade"
   echo "[ESVA] These will be resolved later on in the upgrade process"
   sleep 10
   FUNCTION-FileList
fi
}

#############################################
# Grabbing a working mirror                 #
#############################################
function FUNCTION-FileList()
{
cd /tmp
if [ -f /tmp/$filelist ]; then
   mv $filelist $filelist.old
fi

echo "[ESVA] Grabbing file list from $PM1"
wget $PM1/$filelist
if [ -f /tmp/$filelist ]; then
   if [ "`head -1 $filelist`" == '#ESVA-FILELIST#' ]; then
      echo "[ESVA] Got a filelist."
      DLHOST="$PM1"
   fi
else
   echo "[ESVA] failed to get $PM1/$filelist trying second server."
   wget $PM2/$filelist
   if [ -f /tmp/$filelist ]; then
      if [ "`head -1 $filelist`" == '#ESVA-FILELIST#' ]; then
         echo "[ESVA] Got a filelist."
         DLHOST="$PM2"
      fi
   else
      echo "[ESVA] failed to get $PM2/$filelist trying last server."
      wget $PM3/$filelist
      if [ -f /tmp/$filelist ]; then
         if [ "`head -1 $filelist`" == '#ESVA-FILELIST#' ]; then
            echo "[ESVA] Got a filelist."
            DLHOST="$PM3"
         fi
      else
         echo "[ESVA] No available servers to get the file list, please try again later"
      fi
   fi
fi
echo "[ESVA] using $DLHOST as mirror"
DLLOC=$DLHOST/update/$sVERSION

FUNCTION-ESVA2059
}
#############################################

#############################################
# 2059 updates				    #
#############################################
function FUNCTION-ESVA2059()
{
echo "[ESVA] Starting 2.0.5.9 updates "

echo "[ESVA] - Updating versions of esva-xxx scripts for better handling of no commandline arguments...  "
sleep 1
	cd /usr/local/sbin
    echo "[ESVA] -- Backing up scripts... "
    tar cvzf pre$sVERSION.tgz *
    rm -f esva-domainshow
    rm -f esva-mwusershow
    /usr/bin/wget $DLLOC/esva-domainshow
    /usr/bin/wget $DLLOC/esva-mwusershow
    chmod 744 *

echo "[ESVA] - Updating KAM.cf.sh for silent operation and better recovery... "
sleep 1
    cd /etc/cron.daily
    rm -f KAM.cf.sh
    /usr/bin/wget $DLLOC/KAM.cf.sh
    chmod 744 KAM.cf.sh

echo "[ESVA] - Updating Postfix's configuration... "
sleep 1
    cd /etc/postfix
    cp main.cf main.cf.pre$sVERSION
    postmap /etc/postfix/virtual
    postconf -e "smtpd_client_restrictions = permit_sasl_authenticated, reject_rbl_client zen.spamhaus.org"
    service postfix reload
	
echo "[ESVA] - Tuning httpd to run a bit leaner... "
sleep 1
    service httpd stop
    cd /etc/httpd/conf/
    mv httpd.conf httpd.conf.pre$sVERSION
    /usr/bin/wget $DLLOC/httpd.conf
    chmod 644 httpd.conf
    service httpd start
	
echo "[ESVA] - Configuring MySql to only listen to localhost... "
sleep 1
    if [ `grep bind-address /etc/my.cnf` ]; then
        echo " -- MySQL is already bound to localhost - skipping... "
    else
        cp /etc/my.cnf /etc/my.cnf.pre$sVERSION
        sed -i '/\[mysqld\]/ a bind-address=127.0.0.1' /etc/my.cnf
        service mysqld restart
    fi

echo "[ESVA] - Forcing Webmin to only listen to localhost... "
sleep 1
    if [ `grep allow= /etc/webmin/miniserv.conf` ]; then
        echo "[ESVA] -- Webmin is already bound to localhost - skipping... "
    else
        echo "allow=127.0.0.1">>/etc/webmin/miniserv.conf
        service webmin restart
    fi
	
echo "[ESVA] - Configuring weekly SQLGrey updates... "
sleep 1
    ln /usr/sbin/update_sqlgrey_config /etc/cron.weekly/update_sqlgrey_config
    /etc/cron.weekly/update_sqlgrey_config

echo "[ESVA] - Adjusting SA scores for a few rules... "
sleep 1
    sed -i '/^score FUZZY_OCR_KNOWN_HASH/d' /etc/MailScanner/spam.assassin.prefs.conf
    echo "score FUZZY_OCR_KNOWN_HASH 0.1">>/etc/MailScanner/spam.assassin.prefs.conf
    sed -i '/^score RCVD_IN_DNSWL_LOW/d' /etc/MailScanner/spam.assassin.prefs.conf
    echo "score RCVD_IN_DNSWL_LOW 0.0">>/etc/MailScanner/spam.assassin.prefs.conf

echo "[ESVA] Done with the 2.0.5.9 updates "
sleep 2

FUNCTION-SystemUpgrade1
}
#############################################

#############################################
# Upgrade the system to latest version	    #
#############################################
function FUNCTION-SystemUpgrade1()
{
echo "[ESVA] Upgrading the system part 1"
sleep 2

 #Clean up YUM to avoid unsubscriptable errors
 yum clean all

 echo "[ESVA] - Backing up yum configs "
 sleep 1
 mv /etc/yum.conf /etc/yum.conf.pre$sVERSION
 
 echo "[ESVA] - Setting new yum configs "
 cd /etc/
 /usr/bin/wget $DLLOC/yum.conf
 mv /etc/yum.repos.d/rpmforge.repo /etc/yum.repos.d/rpmforge.repo.pre$sVERSION
 cd /etc/yum.repos.d
 /usr/bin/wget $DLLOC/rpmforge.repo
 
 #Configure YUM Priorities
 yum install yum-priorities -y
 echo 'priority=1'>>/etc/yum.repos.d/CentOS-Base.repo
 echo 'priority=1'>>/etc/yum.repos.d/CentOS-Media.repo
 if [ -f /etc/yum.repos.d/XenSource.repo ]; then
      echo 'priority=5'>>/etc/yum.repos.d/XenSource.repo
 fi
 echo 'priority=10'>>/etc/yum.repos.d/rpmforge.repo

 # Temporary globally disable perl updates until mailscanner install is complete
 echo 'exclude=perl'>>/etc/yum.conf

 #Stop MailScanner before we go any further
 service MailScanner stop
 
 #Remove some problematc packages and update the system
 #Removed packages will be re-installed by the MailScanner update.
echo "[ESVA] - Remove some packages "
 sleep 1
 rpm -e --nodeps perl-Math-BigRat
 rpm -e --nodeps perl-bignum
 rpm -e --nodeps perl-File-Temp
 rpm -e --nodeps perl-Math-BigInt

 #Update installed packages
 echo "[ESVA] Start system upgrade "
 sleep 2
 yum update yum -y
 yum update --skip-broken -y
 
 #Silence errors logged during WebMin startup
 yum install pam-devel perl-Authen-PAM -y
 echo '#%PAM-1.0'>/etc/pam.d/webmin
 echo 'auth  required pam_nologin.so'>>/etc/pam.d/webmin
 echo 'auth  include   system-auth'>>/etc/pam.d/webmin
 echo 'accountinclude  system-auth'>>/etc/pam.d/webmin
 echo 'password   include  system-auth'>>/etc/pam.d/webmin
 echo 'sessioninclude  system-auth'>>/etc/pam.d/webmin
 echo " Done system upgrade part 1 "

FUNCTION-MailScanner
}
#############################################

#############################################
# Upgrade Mailscanner 			    #
#############################################
function FUNCTION-MailScanner()
{
echo "[ESVA] Upgrading mailscanner to 4.84.3-1 "
sleep 1
  service MailScanner stop
  cd /tmp
  wget http://www.mailscanner.info/files/4/rpm/MailScanner-4.84.3-1.rpm.tar.gz
  tar -xvzf MailScanner-*.rpm.tar.gz
  cd MailScanner*
  ./install.sh
  service sendmail stop
  chkconfig sendmail off
  chkconfig MailScanner on
  cd /etc/MailScanner
  upgrade_MailScanner_conf MailScanner.conf MailScanner.conf.rpmnew > MailScanner.new
  mv -f MailScanner.conf MailScanner.old
  mv -f MailScanner.new  MailScanner.conf
  cd /tmp
  rm -rf MailScanner*

  #Fix known problems caused by the MailScanner upgrade process
  sed -i '/^Incoming Queue Dir/ c\Incoming Queue Dir = \/var\/spool\/postfix\/hold' /etc/MailScanner/MailScanner.conf
  echo "[ESVA] Done Upgrading mailscanner to 4.84.3-1 "
sleep 2

FUNCTION-SpamAssassin
}
#############################################

#############################################
# Upgrade SpamAssassin to latest	    #
############################################# 
function FUNCTION-SpamAssassin()
{
 echo "[ESVA] Upgrading SpamAssasin to Latest "
    cd /tmp
    wget http://www.mailscanner.info/files/4/install-Clam-SA-latest.tar.gz
    tar -xvzf install-Clam-SA-latest.tar.gz
    cd install-Clam*
    echo 'n'>answers.txt
    echo ''>>answers.txt
    cat answers.txt|./install.sh
    cd /tmp
    rm -rf install-Clam*
	
	# remove old files 
	rm /var/clamav/daily.cld
	rm /var/clamav/main.cld
	
    #Force an update of ClamAV definitions...
    service clamd restart
    freshclam
	
	# fix socket file in mailscanner.conf
	sed -i '/^Clamd Socket/ c\Clamd Socket = \/var\/run\/clamav\/clamd.sock' /etc/MailScanner/MailScanner.conf
	
	echo "[ESVA] - Restarting MailScanner after all these changes..."
    service MailScanner restart

echo "[ESVA] Done upgrading SpamAssasin to Latest "

FUNCTION-SystemUpgrade2
}
#############################################

#############################################
# Upgrade system part 2			    #
#############################################
function FUNCTION-SystemUpgrade2()
{
echo "[ESVA] Upgrading the system part 2"
sleep 2

sed -i "/exclude=perl*/d" /etc/yum.conf
echo 'exclude=perl-IO perl-Scalar-List-Utils perl-bignum perl-Test-Harness perl-Test-Simple perl-Sys-Syslog perl-File-Temp perl-Math-BigRat'>>/etc/yum.repos.d/rpmforge.repo

yum update -y

echo "[ESVA] Done Upgrading the System"
sleep 2

FUNCTION-PingHome
}
#############################################

#############################################
# Ping home	 			    #
#############################################
function FUNCTION-PingHome()
{
echo "[ESVA] Modifying PingHome"
sleep 2

rm /etc/cron.monthly/GD-Check
cd /etc/cron.monthly
wget $DLLOC/Ping-Home
chmod 755 Ping-Home

FUNCTION-WebInterface
}
#############################################

#############################################
# Start update the webinterface             #
############################################# 
function FUNCTION-WebInterface()
{
echo "[ESVA] Changing links in the webinterface"
  cd /tmp
  sed -i '/ESVA Website/ c\    <LI><A HREF=\"http:\/\/www.esvacommunity.com\">ESVA Website<\/A>' $wwwpath/other.php
  sed -i '/ESVA Support Forum/ c\    <LI><A HREF=\"http:\/\/www.esvacommunity.com\/forum\">ESVA Support Forum<\/A>' $wwwpath/other.php
  sed -i '/Sam Spad/d' $wwwpath/other.php
  sed -i '/DNS Report/d' $wwwpath/other.php
  rm $wwwpath/images/ESVA-logo.gif
  wget $DLLOC/ESVA-logo.gif
  mv ESVA-logo.gif $wwwpath/images/

echo "[ESVA] Done changing links in the webinterface"

FUNCTION-esva-update-File
}
#############################################

#############################################
# Update esva-update file		    #
#############################################
function FUNCTION-esva-update-File()
{

echo "[ESVA] Creating new esva-update file"
cd /usr/local/sbin/
wget $DLLOC/esva-update
chmod 755 esva-update

FUNCTION-IssueFile
}
#############################################
# Write new issue file			    #
#############################################
function FUNCTION-IssueFile()
{
echo "[ESVA] Writing new issue file. "
sleep 1
mv /etc/issue /etc/issue.pre$sVERSION
echo " *********************************************** " > /etc/issue
echo " * Email Security Virtual Appliance (ESVA)     * " >> /etc/issue
echo " * v $VERSION 			             * " >> /etc/issue
echo " *                                             * " >> /etc/issue
echo " * http://www.esvacommunity.com/               * " >> /etc/issue
echo " *                                             * " >> /etc/issue
echo " *********************************************** " >> /etc/issue
echo " " >> /etc/issue
echo " Kernel \r on an \m " >> /etc/issue
echo " " >> /etc/issue
echo " " >> /etc/issue
echo "................................................. " >> /etc/issue

FUNCTION-VersionFile
}
#############################################

#############################################
# Write new Version file		    #
#############################################
function FUNCTION-VersionFile()
{
echo "[ESVA] Writing new version file. "
sleep 2
mv /var/esva/$sVERSION.started /var/esva/$sVERSION
echo "$VERSION">/var/esva/currentversion
echo "[ESVA] Completed the $VERSION update at " `date`
sleep 2
init 6 
}
#############################################


#############################################
# Where to start                            #
#############################################
echo "[ESVA] Did you make a snapshot of your system?  "
echo "[ESVA] You will now have 20 Seconds to abort (CTRL C) "
sleep 20

echo "[ESVA] Staring ESVA $VERSION update "
touch /var/esva/$sVERSION.started

VersionCheck
#############################################
#EOF
